# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bestcoder_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='codeforces_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hduoj_username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
