# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='problem_permission',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(default='Regular User', max_length=24),
        ),
    ]
