# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-23 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_zone',
        ),
    ]
