# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160925_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_password_token_create_time',
            new_name='reset_password_token_expire_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_extra_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='problems_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='problems_status',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(default='regular_user', max_length=24),
        ),
    ]
