# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 06:22
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170830_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_keys',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
