# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_session_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='github',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='/static/avatar/default.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
