# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180501_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
