# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180501_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
