# Generated by Django 2.1.7 on 2020-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200420_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sighin_time',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
