# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfa_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
