# Generated by Django 2.1.7 on 2020-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200421_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title_color',
            field=models.TextField(null=True),
        ),
    ]
