# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20151212_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminGroup',
        ),
        migrations.AddField(
            model_name='user',
            name='openapi_appkey',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
