# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20160217_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forbidden',
            field=models.BooleanField(default=False),
        ),
    ]
