# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_is_forbidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='accepted_number',
            new_name='accepted_problem_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
    ]
