# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20160424_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='submissions_number',
            new_name='submission_number',
        ),
    ]
