# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20160424_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_forbidden',
            new_name='is_disabled',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='openapi_appkey',
            new_name='open_api_appkey',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='problems_status',
        ),
        migrations.AddField(
            model_name='user',
            name='admin_extra_permission',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='open_api',
            field=models.BooleanField(default=False),
        ),
    ]
