# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='key',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
