# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20180501_0436'),
    ]

    operations = [
        migrations.RunSQL("""
        DELETE FROM options_sysoptions WHERE key = 'languages';
        """)
    ]
