# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import utils.models
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.shortcuts.rand_str, max_length=32, primary_key=True, serialize=False)),
                ('contest_id', models.IntegerField(db_index=True, null=True)),
                ('problem_id', models.IntegerField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('code', utils.models.RichTextField()),
                ('result', models.IntegerField(default=6)),
                ('info', jsonfield.fields.JSONField(default={})),
                ('language', models.CharField(max_length=20)),
                ('shared', models.BooleanField(default=False)),
                ('accepted_time', models.IntegerField(blank=True, null=True)),
                ('accepted_info', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'db_table': 'submission',
            },
        ),
    ]
