# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(),
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='accepted_info',
            new_name='statistic_info',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='accepted_time',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-create_time',)},
        )
    ]
