# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20170509_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='accepted_info',
            new_name='statistic_info',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='accepted_time',
        ),
    ]
