# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20170830_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
