# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20151207_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='judge_end_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
