# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20170923_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
