# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_fix_submission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='username',
            field=models.TextField(),
        ),
    ]
