# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_join',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
