# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_joingrouprequest_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='created_by',
        ),
    ]
