# Generated by Django 2.1.7 on 2020-07-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ('floor',)},
        ),
    ]
