# Generated by Django 2.1.7 on 2020-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200718_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumreply',
            name='is_top',
        ),
    ]
