# Generated by Django 2.1.7 on 2020-08-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forumreply_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='son_sort',
        ),
    ]
