# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-17 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170209_0845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ContestProblem',
        ),
    ]
