# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-23 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20170717_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmcontestrank',
            old_name='total_ac_number',
            new_name='accepted_number',
        ),
        migrations.RenameField(
            model_name='acmcontestrank',
            old_name='total_submission_number',
            new_name='submission_number',
        ),
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='total_submission_number',
            new_name='submission_number',
        ),
    ]
