# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20171011_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestannouncement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
