# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_contestannouncement_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allowed_ip_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
