# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20151017_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='vj_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='vj_problem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='test_case_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
