# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_contestproblem_spj'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='vj_problem_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
