# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_dispatcher', '0004_auto_20160407_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeserver',
            name='left_instance_number',
        ),
        migrations.RemoveField(
            model_name='judgeserver',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='judgeserver',
            name='workload',
        ),
        migrations.AddField(
            model_name='judgeserver',
            name='used_instance_number',
            field=models.IntegerField(default=0),
        ),
    ]
