# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCaseScore',
        ),
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='rule_type',
            field=models.CharField(default='ACM', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='test_case_score',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=utils.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=utils.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='spj_language',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
