# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='_id',
            field=models.CharField(db_index=True, default='1', max_length=24, unique=True),
            preserve_default=False,
        ),
    ]
