# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 08:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20170202_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
