# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20170217_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='total_accepted_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='total_submit_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='total_accepted_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='total_submit_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
