# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20170823_0918'),
        ('problem', '0006_auto_20170823_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='_id',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('_id', 'contest')]),
        ),
        migrations.DeleteModel(
            name='ContestProblem',
        ),
    ]
