# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 12:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20170923_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('create_time',)},
        ),
    ]
