# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_fix_problem_ac_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=utils.models.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rule_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='spj_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='spj_language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='spj_version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problemtag',
            name='name',
            field=models.TextField(),
        ),
    ]
