# Generated by Django 2.1.7 on 2019-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_problem_io_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='share_submission',
            field=models.BooleanField(default=False),
        ),
    ]
