# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=128)),
                ('port', models.IntegerField(default=25)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('tls', models.BooleanField()),
            ],
            options={
                'db_table': 'smtp_config',
            },
        ),
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='http://127.0.0.1', max_length=128)),
                ('name', models.CharField(default='Online Judge', max_length=32)),
                ('name_shortcut', models.CharField(default='oj', max_length=32)),
                ('website_footer', models.TextField(default='Online Judge Footer')),
                ('allow_register', models.BooleanField(default=True)),
                ('submission_list_show_all', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_config',
            },
        ),
    ]
