# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JudgeServerToken',
        ),
        migrations.DeleteModel(
            name='SMTPConfig',
        ),
        migrations.DeleteModel(
            name='WebsiteConfig',
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='hostname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='judger_version',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='service_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
