# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20161119_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=32)),
                ('judger_version', models.CharField(max_length=24)),
                ('cpu_core', models.IntegerField()),
                ('memory_usage', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('last_heartbeat', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('task_number', models.IntegerField()),
            ],
            options={
                'db_table': 'judge_server',
            },
        ),
    ]
