# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_judgeserver_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeserver',
            name='hostname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='judger_version',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='service_url',
            field=models.TextField(null=True),
        ),
    ]
