# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_judgeserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeserver',
            name='service_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
