# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_auto_20161120_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'judge_server_token',
            },
        ),
    ]
